import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/widget.css" />
      </head>
      <body
        className={ `${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        { children }
        <script
          src="widget.iife.js"
          data-business-id="1"
          defer
        ></script>
      </body>
    </html>
  );
}
